# Generated by Django 3.0.8 on 2020-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=220)),
                ('image', models.ImageField(upload_to='about/')),
                ('description', models.TextField()),
            ],
        ),
    ]
