# Generated by Django 3.0.8 on 2020-07-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20200730_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file_upload',
        ),
        migrations.CreateModel(
            name='SampleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('file_upload', models.FileField(upload_to='documents/')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.Categorie')),
            ],
        ),
    ]
