# Generated by Django 3.0.8 on 2020-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200730_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
