# Generated by Django 3.0.8 on 2020-08-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20200730_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date', '-update_date']},
        ),
    ]
