# Generated by Django 3.0.8 on 2020-08-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
